// Generated by Wrangler on Sat Sep 14 2024 14:54:41 GMT+0300 (Москва, стандартное время)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	STORAGE: R2Bucket;
	DATABASE: D1Database;
}
